version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/code/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - REDIS_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A taxedwebsite worker -l INFO
    volumes:
      - .:/user/src/code
    env_file:
      - ./.env
    depends_on:
      - django
      - redis
  redis:
    image: "redis:alpine"


