# Generated by Django 4.1.7 on 2023-04-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_customer_user_invoice_user_product_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
    ]
