# Generated by Django 4.1.7 on 2023-04-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_invoice_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice'),
        ),
    ]
