# Generated by Django 4.1.7 on 2023-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_product_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_wo_VAT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
